baseURL = "https://toplak.io/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Marko Toplak"


[languages]
  [languages.en]
    languageName = "English"
    weight = 1
  [languages.sl]
    languageName = "Slovenščina"
    weight = 2


[[languages.en.menu.main]]
    name = "Index"
    url = "/"
    weight = 1

[[languages.sl.menu.main]]
    name = "Kazalo"
    url = "/sl/"
    weight = 1
