name: Push to GitHub Pages on push to master
on:
  schedule:
    # every day at midnight: https://crontab.guru/every-midnight
    - cron:  '0 0 * * *'

  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Build hugo page
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.63.2/hugo_0.63.2_Linux-64bit.deb
          sudo dpkg -i hugo*.deb
          rm -rf public 2> /dev/null
          rm *.deb

      - name: Build page
        run: |
          hugo
          echo 'toplak.io' > public/CNAME
          touch public/.nojekyll

      # Deploy to local repo
      - name: Deploy
        if: github.ref == 'refs/heads/master'
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: public
          SKIP_EMPTY_COMMITS: True
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.5.4
        with:
          args: "--verbose --no-progress './public/**/*.html'"
          fail: true